#!/bin/bash
#SBATCH -J rcb_24           # job name
#SBATCH -o rcb_24.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 16             # total number of mpi tasks requested
#SBATCH -p largemem     # queue (partition) -- normal, development, etc.
#SBATCH -t 48:00:00        # run time (hh:mm:ss)

nproc=$SLURM_NTASKS
nprocm1=$(($nproc-1))
for i in `seq 0 ${nprocm1}`; do
  mkdir -p /scratch/01022/tg802750/1024/rcbdata_24/$i
done

/usr/bin/time -p ibrun ./rcb insf /scratch/01022/tg802750/1024/rcbdata_24 /scratch/01022/tg802750/1024/vecdata_24
