#!/bin/bash
#SBATCH -J sf3d           # job name
#SBATCH -o sf3d.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 16             # total number of mpi tasks requested
#SBATCH -p largemem     # queue (partition) -- normal, development, etc.
#SBATCH -t 10:00:00        # run time (hh:mm:ss)

nproc=$SLURM_NTASKS
nprocm1=$(($nproc-1))
for i in `seq 0 ${nprocm1}`; do
  mkdir -p /scratch/01022/tg802750/1024/sfdata_26/$i
done

/usr/bin/time -p ibrun ./sf3 insf /scratch/01022/tg802750/1024/sfdata_10 /scratch/01022/tg802750/1024/vecdata_10             # run 
